version: '3.8'

networks:
  web4react:

services:
  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    container_name: web4react_backend
    networks:
      - web4react
    ports:
      - "3210:3210"
      - "9010:9010"
      - "9011:9011"
    environment:
      JAVA_TOOL_OPTIONS: >
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.host=0.0.0.0
        -Dcom.sun.management.jmxremote.local.only=false
        -Dcom.sun.management.jmxremote.port=9010
        -Dcom.sun.management.jmxremote.rmi.port=9011
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.authenticate=false
        -Djava.rmi.server.hostname=host.docker.internal
    command: ["java", "-jar", "/opt/project/target/web-0.0.1-SNAPSHOT.jar"]

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: web4react_frontend
    networks:
      - web4react
    depends_on:
      - backend
    ports:
      - "80:80"
